# Generated by Django 3.2.16 on 2023-01-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_auth', '0004_membermodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('created', models.DateField(auto_now=True)),
                ('friday', models.ManyToManyField(related_name='friday_plan', to='App_main.Workout')),
                ('monday', models.ManyToManyField(related_name='monday_plan', to='App_main.Workout')),
                ('saturday', models.ManyToManyField(related_name='saturday_plan', to='App_main.Workout')),
                ('sunday', models.ManyToManyField(related_name='sunday_plan', to='App_main.Workout')),
                ('thursday', models.ManyToManyField(related_name='thursday_plan', to='App_main.Workout')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_follower', to='App_auth.membermodel')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_provider', to='App_auth.trainermodel')),
                ('tuesday', models.ManyToManyField(related_name='tuesday_plan', to='App_main.Workout')),
                ('wednesday', models.ManyToManyField(related_name='wednesday_plan', to='App_main.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='DietChartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_breakfast', models.CharField(max_length=500)),
                ('sunday_lunch', models.CharField(max_length=500)),
                ('sunday_dinner', models.CharField(max_length=500)),
                ('sunday_snacks', models.CharField(max_length=500)),
                ('monday_breakfast', models.CharField(max_length=500)),
                ('monday_lunch', models.CharField(max_length=500)),
                ('monday_dinner', models.CharField(max_length=500)),
                ('monday_snacks', models.CharField(max_length=500)),
                ('tuesday_breakfast', models.CharField(max_length=500)),
                ('tuesday_lunch', models.CharField(max_length=500)),
                ('tuesday_dinner', models.CharField(max_length=500)),
                ('tuesday_snacks', models.CharField(max_length=500)),
                ('wednesday_breakfast', models.CharField(max_length=500)),
                ('wednesday_lunch', models.CharField(max_length=500)),
                ('wednesday_dinner', models.CharField(max_length=500)),
                ('wednesday_snacks', models.CharField(max_length=500)),
                ('thursday_breakfast', models.CharField(max_length=500)),
                ('thursday_lunch', models.CharField(max_length=500)),
                ('thursday_dinner', models.CharField(max_length=500)),
                ('thursday_snacks', models.CharField(max_length=500)),
                ('friday_breakfast', models.CharField(max_length=500)),
                ('friday_lunch', models.CharField(max_length=500)),
                ('friday_dinner', models.CharField(max_length=500)),
                ('friday_snacks', models.CharField(max_length=500)),
                ('saturday_breakfast', models.CharField(max_length=500)),
                ('saturday_lunch', models.CharField(max_length=500)),
                ('saturday_dinner', models.CharField(max_length=500)),
                ('saturday_snacks', models.CharField(max_length=500)),
                ('created', models.DateField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_follower', to='App_auth.membermodel')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_provider', to='App_auth.trainermodel')),
            ],
        ),
    ]
