# Generated by Django 3.2.16 on 2023-01-25 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_main', '0002_rename_created_dietchartmodel_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=6)),
                ('bmi', models.FloatField()),
                ('weight_status', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmi_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
