# Generated by Django 3.2.16 on 2023-02-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0005_rename_weeklyupdatemodel_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='receiver_seen',
            field=models.BooleanField(default=False),
        ),
    ]
