# Generated by Django 3.2.16 on 2022-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0003_alter_membermodel_my_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
